InterfaceApp/urls.py
from django.urls import path, include
from . import views

app_name = 'InterfaceApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name="logout"),
    path('performance/', views.performance, name='performance'),
    path('signup/', views.signup, name='signup'),
    path('apitest/', views.apitest, name='apitest'),
    path('wishlist/', views.wishlist, name='wishlist'),

    path('wishlist/del/', views.del_wishlist, name='wishlist_d'),
    path('wishlist/add/', views.add_wishlist, name='wishlist_c'),
    path('profile/', views.profile, name='profile'),
    path('news/', views.news, name='news'),
]

InterfaceProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('InterfaceApp.urls')),
    path('blogapp/', include('blogapp.urls')),
    path('', include('InterfaceApp.urls')),
]

blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view()),
    # path('<int:pk>/', views.single_post_page),
    # path('', views.index),
]

InterfaceApp/models.py
from django.db import models
from django.contrib.auth.models import User

class PerformanceDB(models.Model):
    seq = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    startDate = models.DateField()
    endDate = models.DateField()
    place = models.CharField(max_length=50)
    realmName = models.CharField(max_length=10)
    area = models.CharField(max_length=10, null=True)
    thumbnail = models.BinaryField()
    gpsX = models.FloatField(null=True)
    gpsY = models.FloatField(null=True)

    def __str__(self):
        return f"seq: {self.seq}, title: {self.title}, startDate: {self.startDate}, endDate: {self.endDate}, place: {self.place}, realmName: {self.realmName}, area: {self.area}, thumbnail: {self.thumbnail}, gpsX: {self.gpsX}, gpsY: {self.gpsY}"

class WishlistDB(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, db_column="user_id")
    performance_seq = models.ForeignKey(PerformanceDB, on_delete=models.CASCADE, db_column="performance_seq")

InterfaceApp/views.py
from collections import OrderedDict

from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from .models import PerformanceDB, WishlistDB
from django.core.paginator import Paginator
import random
import math
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

def index(request):
    context = None
    logineduser = False
    if request.user.is_authenticated:
        logineduser = request.user.first_name + request.user.last_name
    posters = PerformanceDB.objects.values_list('thumbnail', flat=True)
    pick = random.sample(list(posters), 6)
    context = {'logineduser': logineduser,
               'poster1': pick[0],
               'poster2': pick[1],
               'poster3': pick[2],
               'poster4': pick[3],
               'poster5': pick[4],
               'poster6': pick[5],
               }
    return render(request, "index.html", context)

def login(request):
    if request.method == "POST":
        useremail = request.POST.get('useremail', None)
        password = request.POST.get('password', None)
        user = auth.authenticate(username=useremail, password=password)
        if user is not None :
            auth.login(request, user)
            return redirect("InterfaceApp:index")
        else :
            return render(request, 'login.html', {'error': '※ 사용자 아이디 또는 패스워드가 틀립니다.'})
    else :
        return render(request, 'login.html',)


def performance(request):
    # TODO: 로딩속도 개선 -> 링크 이미지를 파일로 db에 저장??
    # 검색 기능
    if request.GET.get('performance_search'):
        performance_search = request.GET.get('performance_search')     # 검색 결과 받아오기
        performance_lists = PerformanceDB.objects.filter(title__contains=performance_search)  # DB에서 title에 검색 결과가 포함되어 있는 값
    # 기간 선택 기능
    elif request.GET.get('date'):
        date_search = request.GET.get('date')     # 검색 결과 받아오기
        performance_lists = PerformanceDB.objects.filter(startDate__lte=date_search, endDate__gte=date_search)  # DB에서 title에 검색 결과가 포함되어 있는 값
        print(request.GET.get('date'))
    # 지역 선택 기능
    elif request.GET.get('area'):
        area_list = request.GET.getlist('area')
        performance_lists = PerformanceDB.objects.filter(area__in=area_list)  # DB에서 title에 검색 결과가 포함되어 있는 값
        page = request.GET.get('page', 1)  # 페이지
        paginator = Paginator(performance_lists, 10)  # 페이지 당 n개씩 보여주기
        page_obj = paginator.get_page(page)

        # url 중첩 방지를 위한 url path slicing
        current_path = request.get_full_path()
        print(current_path)
        current_path = current_path[current_path.find('?') + 1:]
        if current_path.find('page') != -1:
            current_path = current_path[:current_path.find('&page')]
        context = {
            'performance_list': page_obj,
            'current_path': current_path,
            'area_list': area_list
        }
        return render(request, "performance.html", context)
    # 분류 선택 기능
    elif request.GET.get('classification'):
        classification_list = request.GET.getlist('classification')
        performance_lists = PerformanceDB.objects.filter(realmName__in=classification_list)  # DB에서 title에 검색 결과가 포함되어 있는 값
        page = request.GET.get('page', 1)  # 페이지
        paginator = Paginator(performance_lists, 10)  # 페이지 당 n개씩 보여주기
        page_obj = paginator.get_page(page)

        # url 중첩 방지를 위한 url path slicing
        current_path = request.get_full_path()
        print(current_path)
        current_path = current_path[current_path.find('?') + 1:]
        if current_path.find('page') != -1:
            current_path = current_path[:current_path.find('&page')]
        context = {
            'performance_list': page_obj,
            'current_path': current_path,
            'classification_list': classification_list
        }
        return render(request, "performance.html", context)
    # 정렬 선택 기능
    elif request.GET.get('orderby'):
        orderby_list = request.GET.getlist('orderby')
        if orderby_list[0] == '거리':
            current_latitude = float(request.GET.get('latitude'))
            current_longitude = float(request.GET.get('longitude'))
            distanceDict = OrderedDict()
            for i in range(len(PerformanceDB.objects.all())):
                distanceDict[PerformanceDB.objects.all().values()[i]['seq']] = math.sqrt((current_latitude-PerformanceDB.objects.all().values()[i]['gpsY'])**2 + (current_longitude-PerformanceDB.objects.all().values()[i]['gpsX'])**2)
            distanceDict = dict(sorted(distanceDict.items(), key=lambda x: x[1]))
            orderby_distance_list = list(distanceDict)
            orderby_lists = PerformanceDB.objects.filter(seq=orderby_distance_list[0])
            print(orderby_lists)
            for i in range(1, len(PerformanceDB.objects.all())):
                orderby_lists = orderby_lists|PerformanceDB.objects.filter(seq=orderby_distance_list[i])
        elif orderby_list[0] == '제목':
            orderby_lists = PerformanceDB.objects.all().order_by('title')
        elif orderby_list[0] == '시작일':
            orderby_lists = PerformanceDB.objects.all().order_by('startDate')
        elif orderby_list[0] == '마감일':
            orderby_lists = PerformanceDB.objects.all().order_by('endDate')
        page = request.GET.get('page', 1)  # 페이지
        paginator = Paginator(orderby_lists, 10)  # 페이지 당 n개씩 보여주기
        page_obj = paginator.get_page(page)

        # url 중첩 방지를 위한 url path slicing
        current_path = request.get_full_path()
        current_path = current_path[current_path.find('?') + 1:]
        if current_path.find('page') != -1:
            current_path = current_path[:current_path.find('&page')]
        context = {
            'performance_list': page_obj,
            'current_path': current_path,
            'orderby_list': orderby_list
        }
        return render(request, "performance.html", context)
    # 조회 기능 사용x 시
    else:
        performance_lists = PerformanceDB.objects.all()


    page = request.GET.get('page', 1)  # 페이지
    paginator = Paginator(performance_lists, 10)  # 페이지 당 n개씩 보여주기
    page_obj = paginator.get_page(page)

    # url 중첩 방지를 위한 url path slicing
    current_path = request.get_full_path()
    current_path = current_path[current_path.find('?')+1:]
    if current_path.find('page') != -1:
        current_path = current_path[:current_path.find('&page')]

    # WishlistDB 등록 여부 확인
    #if request.user.is_authenticated:
    #    user_id = request.user.id
    #    seqs = WishlistDB.objects.filter(user_id=user_id).values_list('performance_seq', flat=True)
    #else:
    #    seqs = None

    context = {
        'performance_list': page_obj,
        'current_path': current_path,
    #    'seqs': seqs
    }
    return render(request, "performance.html", context)

def signup(request):
    res_data = None
    if request.method == 'POST':
        useremail = request.POST.get('useremail')
        firstname = request.POST.get('first_name')
        lastname = request.POST.get('last_name')
        password = request.POST.get('password')
        re_password = request.POST.get('confirm_password')
        res_data = {}
        if User.objects.filter(username=useremail):
            res_data['error'] = '※ 이미 가입된 이메일 주소 입니다.'
        elif password != re_password:
            res_data['error'] = '※ 비밀번호가 다릅니다.'
        else:
            user = User.objects.create_user(username=useremail,
                                            first_name=firstname,
                                            last_name=lastname,
                                            password=password)
            auth.login(request, user)
            return redirect("InterfaceApp:index")
    return render(request, 'signup.html', res_data)

def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
    return redirect("InterfaceApp:index")

def apitest(request):
    return render(request, 'apitest.html')

def wishlist(request):
    context = None
    user_id = request.user.id
    wish_list = []
    get_list = WishlistDB.objects.filter(user_id=user_id)

    for i in range(len(get_list)):
        wish_list.append(get_list[i].performance_seq)

    context = {
        'wishlist': wish_list,
    }
    return render(request, 'wishlist.html', context)

@csrf_exempt
def add_wishlist(request):
    data = json.loads(request.body)
    wish_item = data['performance_seq']
    user_id = request.user.id

    get_list = WishlistDB.objects.filter(user_id=user_id)
    #print(get_list.values_list('performance_seq', flat=True))
    if wish_item not in get_list.values_list('performance_seq', flat=True):
        row = WishlistDB(user_id=User.objects.get(pk=user_id), performance_seq=PerformanceDB.objects.get(pk=wish_item))
        row.save()
        result = {'result': f"performance_seq {wish_item} added to the WishlistDB"}
    else:
        #row = WishlistDB.objects.get(performance_seq=wish_item)
        #row.delete()
        result = {'result': f"performance_seq {wish_item} is already exist in the WishlistDB"}
    return JsonResponse(result, content_type='application/json')

@csrf_exempt
def del_wishlist(request):
    data = json.loads(request.body)
    wish_item = data['performance_seq']
    user_id = request.user.id

    row = WishlistDB.objects.get(user_id=user_id, performance_seq=wish_item)
    row.delete()

    return render(request, 'wishlist.html')

def mypage(request):
    return render(request, 'mypage.html')

def profile(request):
    return render(request, 'profile.html')

import requests
import json
import os
from newsapi import NewsApiClient
from datetime import datetime, timedelta
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] ="True"
def news(request):
    newsapi = NewsApiClient(api_key="c66416a0443445a896fe5e0eff1b1bc5")
    # topheadlines = newsapi.get_top_headlines(sources='bbc-news')
    now = datetime.now()
    before_one_day =  now - timedelta(days=25)

InterfaceApp/templates/index.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OnCulture</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Presento - v3.9.0
  * Template URL: https://bootstrapmade.com/presento-bootstrap-corporate-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">
      <h1 class="logo me-auto"><a href="/index/">OnCulture<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt=""></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#team">About us</a></li>
          <li><a href="/index/performance/">공연/전시 정보</a></li>
          <li><a href="#">문화 관련 소식</a></li>
          <li class="dropdown"><a href="/index/wishlist/"><span>My Page</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="/index/wishlist/">위시리스트</a></li>
              <li><a href="/index/memberedit/">회원정보 수정</a></li>
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      {% if not logineduser %}
      <a href="/index/login/" class="get-started-btn scrollto">로그인&nbsp; / &nbsp;회원가입</a>
      {% else %}
      <a href="{% url 'InterfaceApp:logout' %}" class="get-started-btn scrollto">로그아웃</a>
      {% endif %}
    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      <div class="row">
        <div class="col-xl-6">
          <h1>Better culture experience with OnCulture<span style="color: #e03a3c;">.</span></h1>
          <h2>우리 지역의 문화생활을 즐겨보세요!</h2><br>
          {% if logineduser %}
          <h2>&#127775;&nbsp;&nbsp;{{logineduser}}님 환영합니다</h2>
          {% endif %}
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Portfolio</h2>
          <p></p>
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">

          </div>
        </div>

        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">

          <div class="col-lg-4 col-md-6 portfolio-item">
            <div class="portfolio-wrap">
              <img src="{{ poster1 }}" class="img-fluid" alt="">

            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item">
            <div class="portfolio-wrap">
              <img src="{{ poster2 }}" class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4></h4>
                <p></p>

              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item">
            <div class="portfolio-wrap">
              <img src="{{ poster3 }}" class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4></h4>
                <p></p>

              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item">
            <div class="portfolio-wrap">
              <img src="{{ poster4 }}" class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4></h4>
                <p></p>

              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item">
            <div class="portfolio-wrap">
              <img src="{{ poster5 }}" class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4></h4>
                <p></p>

              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item">
            <div class="portfolio-wrap">
              <img src="{{ poster6 }}" class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4></h4>
                <p></p>

              </div>
            </div>
          </div>

<!--
          <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">
              <img src="{% static 'assets/img/portfolio/portfolio-9.jpg' %}" class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4>Web 3</h4>
                <p>Web</p>
                <div class="portfolio-links">
                  <a href="{% static 'assets/img/portfolio/portfolio-9.jpg' %}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 3"><i class="bx bx-plus"></i></a>
                  <a href="portfolio-details.html" title="More Details"><i class="bx bx-link"></i></a>
                </div>
              </div>
            </div>
          </div>
-->
        </div>

      </div>
    </section><!-- End Portfolio Section -->

    <!-- ======= Team Section ======= -->
    <section id="team" class="team section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Team</h2>
          <p><strong>OnCulture</strong> 인터페이스 개발 프로젝트 담당자들을 소개합니다.</p>
        </div>

        <div class="row">

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                <img src="{% static 'assets/img/team/team_1.jpg' %}" class="img-fluid" alt="">

              </div>
              <div class="member-info">
                <h4>김승열</h4>
                <span>hsollclaw@gmail.com</span>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="200">
              <div class="member-img">
                <img src="{% static 'assets/img/team/team_2.jpg' %}" class="img-fluid" alt="">

              </div>
              <div class="member-info">
                <h4>서혁준</h4>
                <span>systjgurwns@naver.com</span>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="300">
              <div class="member-img">
                <img src="{% static 'assets/img/team/team_3.jpg' %}" class="img-fluid" alt="">

              </div>
              <div class="member-info">
                <h4>유영일</h4>
                <span>sunforever58@gmail.com  /  조장</span>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="400">
              <div class="member-img">
                <img src="{% static 'assets/img/team/team_4.jpg' %}" class="img-fluid" alt="">
              </div>
              <div class="member-info">
                <h4>이준희</h4>
                <span>ooeeee@naver.com</span>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Team Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>OnCulture<span>.</span></h3>
            <p>

            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#hero">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#team">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/index/performance/">공연/전시 정보</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">문화 관련 뉴스</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="">Web Development</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Presento</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/presento-bootstrap-corporate-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

InterfaceApp/templates/login.html
<!DOCTYPE html>
<html>
<head>
<title>Login Page</title>
<style>
@import url('https://fonts.googleapis.com/css?family=Numans');

html,body{
background-image: url('https://contents.lotteon.com/itemimage/LD/13/85/20/33/4_/0/LD138520334_0_1.jpg/dims/resizef/720X720');
background-size: cover;
background-repeat: no-repeat;
height: 100%;
font-family: 'Numans', sans-serif;
}

.container{
height: 100%;
align-content: center;
}

.card{
height: 370px;
margin-top: auto;
margin-bottom: auto;
width: 400px;
background-color: rgba(0,0,0,0.5) !important;
}

.social_icon span{
font-size: 60px;
margin-left: 10px;
color: #FFC312;
}

.social_icon span:hover{
color: white;
cursor: pointer;
}

.card-header h3{
color: white;
}

.social_icon{
position: absolute;
right: 20px;
top: -45px;
}

.input-group-prepend span{
width: 50px;
background-color: #FFC312;
color: black;
border:0 !important;
}

input:focus{
outline: 0 0 0 0 !important;
box-shadow: 0 0 0 0 !important;

}

.remember{
color: white;
}

.remember input
{
width: 20px;
height: 20px;
margin-left: 15px;
margin-right: 5px;
}

.login_btn{
color: black;
background-color: #FFC312;
width: 100px;
}

.login_btn:hover{
color: black;
background-color: white;
}

.errormsg{
font-family: Georgia;
font-style: italic;
}

.links{
color: white;
}

.links a{
margin-left: 4px;
}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
<div class="d-flex justify-content-center h-100">
<div class="card">
<div class="card-header">
<h3>OnCulture.</h3>
</div>
<div class="errormsg text-center" style="color:red">
{{error}}
</div>
<div class="card-body">
<form method="POST" action="{% url 'InterfaceApp:login'%}">
{% csrf_token %}
<div class="input-group form-group">
<div class="input-group-prepend">
<span class="input-group-text"><i class="fas fa-user"></i></span>
</div>
<input type="text" class="form-control" name="useremail" placeholder="username">

</div>
<div class="input-group form-group">
<div class="input-group-prepend">
<span class="input-group-text"><i class="fas fa-key"></i></span>
</div>
<input type="password" class="form-control" name="password" placeholder="password">
</div>
<div class="form-group">
<input type="submit" value="Login" class="btn float-right login_btn">
</div>
</form>
</div>
<div class="card-footer">
<div class="d-flex justify-content-center links">
Don't have an account?<a href="/index/signup/">Sign Up</a>
</div>
</div>
</div>
</div>
</div>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>
</html>